# This is a basic workflow to help you get started with Actions

name: workflow-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: git clone
        run: git clone https://github.com/apache/incubator-wayang
      - name: cd 
        run: cd incubator-wayang
      - name: git checkout
        uses: actions/checkout@v2
        with:
          repository: apache/incubator-wayang
          ref: b7b6c1ebf65b58f5c03ac2b9fd4c1846ea877d01
      - name: test-compile
        run: mvn test-compile -pl wayang-platforms.wayang-graphch -am
      - name: test
        run: mvn -pl wayang-platforms.wayang-graphch test -Dtest=org.apache.wayang.graphchi.operators.GraphChiPageRankOperatorTest#testExecution
      - name: flaky-test
        run: mvn -pl wayang-platforms.wayang-graphch edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.wayang.graphchi.operators.GraphChiPageRankOperatorTest#testExecution
