# This is a basic workflow to help you get started with Actions

name: workflow-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: git clone
        run: git clone https://github.com/HubSpot/jinjava
      - name: cd 
        run: cd HubSpot/jinjava
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: HubSpot/jinjava
          ref: b428343af85e613805674cd44dad416dfddde09c
      - name: test-compile
        run: mvn test-compile -pl . -am

